import React from "react";
import { getProviders, signIn } from "next-auth/react";
import Head from "next/head";

const signin = ({ providers }) => {
  return (
    <div className="flex justify-center mt-20 space-x-4">
      <Head>
        <title>SignIn | Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img
        src="https://cdn.cms-twdigitalassets.com/content/dam/help-twitter/en/twitter-tips/desktop-assets/ch-01/ch12findphone.png.twimg.1920.png"
        alt="twitter image inside a phone"
        className="object-cover md:w-44 md:h-80 hidden md:inline-flex rotate-6"
      />
      <div className="">
        {Object.values(providers).map((provider) => (
          <div className="flex flex-col items-center" key={provider.name}>
            <img
              src="https://help.twitter.com/content/dam/help-twitter/brand/logo.png"
              alt="twitter logo"
              className="w-36 object-cover"
            />
            <p className="text-center text-sm italic my-10">
              This app is created by Mirko Cosic
            </p>
            <button
              className="bg-red-400 rounded-lg text-white p-3 font-semibold hover:bg-red-500 transition-all"
              onClick={() => signIn(provider.id, { callbackUrl: "/" })}
            >
              Sign In with {provider.name}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};

export default signin;

export async function getServerSideProps() {
  const providers = await getProviders();
  return {
    props: {
      providers,
    },
  };
}
